title: Chanmakara Khuon
description: Cybersecurity Analysist|IT Manager| Microsoft 365 Specialist| Freelancer|
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker

github:
  zip_url: http://example.com/download.zip
  another_url: another value
